/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author macintosh
 */
public class Form_Environments extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Form_Environments() {
           initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        toggleButton11 = new com.raven.swing.toggle.ToggleButton();
        jLabel4 = new javax.swing.JLabel();
        toggleButton12 = new com.raven.swing.toggle.ToggleButton();
        jLabel5 = new javax.swing.JLabel();
        toggleButton13 = new com.raven.swing.toggle.ToggleButton();
        jLabel6 = new javax.swing.JLabel();
        toggleButton14 = new com.raven.swing.toggle.ToggleButton();
        jLabel7 = new javax.swing.JLabel();
        toggleButton15 = new com.raven.swing.toggle.ToggleButton();

        setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("DEV");
        jPanel2.add(jLabel3);
        jPanel2.add(toggleButton11);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("IST");
        jPanel2.add(jLabel4);
        jPanel2.add(toggleButton12);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 127, 127));
        jLabel5.setText("UAT");
        jPanel2.add(jLabel5);
        jPanel2.add(toggleButton13);

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 127, 127));
        jLabel6.setText("PPD");
        jPanel2.add(jLabel6);
        jPanel2.add(toggleButton14);

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 127, 127));
        jLabel7.setText("PRD");
        jPanel2.add(jLabel7);
        jPanel2.add(toggleButton15);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private com.raven.swing.toggle.ToggleButton toggleButton11;
    private com.raven.swing.toggle.ToggleButton toggleButton12;
    private com.raven.swing.toggle.ToggleButton toggleButton13;
    private com.raven.swing.toggle.ToggleButton toggleButton14;
    private com.raven.swing.toggle.ToggleButton toggleButton15;
    // End of variables declaration//GEN-END:variables
}
