/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author macintosh
 */
public class Form_UC_Parametters extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Form_UC_Parametters() {
           initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        comboSuggestionUI1 = new com.raven.swing.ComboSuggestionUI();
        comboSuggestionUI2 = new com.raven.swing.ComboSuggestionUI();
        comboSuggestionUI3 = new com.raven.swing.ComboSuggestionUI();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldSuggestion1 = new com.raven.swing.textfield.TextFieldSuggestion();
        textFieldSuggestion2 = new com.raven.swing.textfield.TextFieldSuggestion();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 14, 0, 14, 0};
        jPanel2Layout.rowHeights = new int[] {0, 7, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("Input UC Trigram");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("Input UC Apcode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel4, gridBagConstraints);

        textFieldSuggestion1.setPreferredSize(new java.awt.Dimension(70, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(textFieldSuggestion1, gridBagConstraints);

        textFieldSuggestion2.setPreferredSize(new java.awt.Dimension(70, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(textFieldSuggestion2, gridBagConstraints);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ComboSuggestionUI comboSuggestionUI1;
    private com.raven.swing.ComboSuggestionUI comboSuggestionUI2;
    private com.raven.swing.ComboSuggestionUI comboSuggestionUI3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private com.raven.swing.textfield.TextFieldSuggestion textFieldSuggestion1;
    private com.raven.swing.textfield.TextFieldSuggestion textFieldSuggestion2;
    // End of variables declaration//GEN-END:variables
}
