/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package data.factory.component;



public class PanelParametters extends javax.swing.JPanel {

    private javax.swing.JLabel trigram_label;
    private javax.swing.JLabel apcode_label;
    private data.factory.swing.TextFieldSuggestion trigram_input;
    private data.factory.swing.TextFieldSuggestion apcode_input;
    
    public PanelParametters() {
           initComponents();
           init();
    }
    private void init() {
        java.awt.GridBagConstraints gridBagConstraints;

        trigram_label = new javax.swing.JLabel();
        apcode_label = new javax.swing.JLabel();
        trigram_input = new data.factory.swing.TextFieldSuggestion();
        apcode_input = new data.factory.swing.TextFieldSuggestion();

        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 14, 0, 14, 0};
        layout.rowHeights = new int[] {0, 7, 0, 7, 0};
        setLayout(layout);

        trigram_label.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        trigram_label.setForeground(new java.awt.Color(127, 127, 127));
        trigram_label.setText("Input UC Trigram");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(trigram_label, gridBagConstraints);

        apcode_label.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        apcode_label.setForeground(new java.awt.Color(127, 127, 127));
        apcode_label.setText("Input UC Apcode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(apcode_label, gridBagConstraints);

        trigram_input.setPreferredSize(new java.awt.Dimension(80, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(trigram_input, gridBagConstraints);

        apcode_input.setPreferredSize(new java.awt.Dimension(80, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        add(apcode_input, gridBagConstraints);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
