/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package data.factory.component;

import javax.swing.JLabel;



public class PanelRoleType extends javax.swing.JPanel {

    private javax.swing.JLabel role_label;
    private data.factory.swing.ComboBoxSuggestion role_input;
    
    public PanelRoleType() {
           initComponents();
           init();
    }
    private void init() {
        java.awt.GridBagConstraints gridBagConstraints;

        role_label = new javax.swing.JLabel();
        role_input = new data.factory.swing.ComboBoxSuggestion();
        role_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "app","own","dfread"}));
        role_input.setEditable(false);


        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 14, 0, 14, 0};
        layout.rowHeights = new int[] {0, 7, 0, 7, 0};
        setLayout(layout);

        role_label.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        role_label.setForeground(new java.awt.Color(127, 127, 127));
        role_label.setText("Select Role Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(role_label, gridBagConstraints);



        role_input.setPreferredSize(new java.awt.Dimension(80, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(role_input, gridBagConstraints);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
